version: '3'
services:
  db:
    image: mysql:8
    ports:
      - "3306:3306"
    environment:
      - MYSQL_USER='root'
      - MYSQL_PASSWORD='my-secret-pw'
      - MYSQL_ROOT_PASSWORD='new_password'
    volumes:
      - /tmp/app/mysqld:/var/run/mysqld
      - ./db:/var/lib/mysql
      - ./db:/always-initdb.d:ro
  web:
    build: .
    entrypoint: ["./wait.sh"]
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - /tmp/app/mysqld:/run/mysqld
    depends_on:
      - db
