# Generated by Django 4.1.3 on 2023-03-07 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_company_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company_order',
            name='Description',
            field=models.CharField(max_length=300),
        ),
    ]
