# Generated by Django 4.1.3 on 2023-02-22 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_session_user_username_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='user_email',
            field=models.CharField(default='UNKNOWN', max_length=40),
            preserve_default=False,
        ),
    ]
