# Generated by Django 4.1.3 on 2023-03-07 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_company_order_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company_order',
            name='Description',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='company_process_step_template',
            name='Step_Name',
            field=models.CharField(max_length=50),
        ),
    ]
