# Generated by Django 4.1.3 on 2023-02-22 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_session_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='session_key',
            field=models.CharField(max_length=60, primary_key=True, serialize=False),
        ),
    ]
