# Generated by Django 4.1.3 on 2023-03-07 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_company_order_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company_process',
            name='Process_Name',
            field=models.CharField(max_length=70),
        ),
    ]
