# Generated by Django 4.1.3 on 2023-03-23 00:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_alter_company_process_process_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='company_order',
            name='Company_Process',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main_app.company_process'),
            preserve_default=False,
        ),
    ]
