# Generated by Django 4.1.3 on 2023-04-05 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_alter_company_order_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='company_order',
            name='Order_URL',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='company_order',
            name='qr_code',
            field=models.ImageField(blank=True, upload_to='qr_codes'),
        ),
    ]
