# Generated by Django 4.1.3 on 2023-04-06 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_company_order_order_url_company_order_qr_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company_order',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
