# Generated by Django 4.1.3 on 2023-04-06 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_alter_company_order_qr_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company_order',
            name='Order_URL',
        ),
        migrations.RemoveField(
            model_name='company_order',
            name='qr_code',
        ),
        migrations.AddField(
            model_name='company_order',
            name='qr_code_img',
            field=models.ImageField(default=None, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='company_order',
            name='qr_url',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
