# Generated by Django 4.1.3 on 2023-04-07 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_remove_company_order_order_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company_order',
            name='qr_code_img',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='company_order',
            name='qr_url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
